### ISSUE TITLE
Characters in IDs can produce subtle bugs

### ISSUE THREAD

**Issue by rbeezer** [BooksHTML/knowls#11]
When knowl content is part of the page (rather than an external file), a `refid` attribute is used to point to the container holding the content.

Certain characters (definitely a period) are a bad idea for value of this attribute.  I suspect they are confusing CSS selectors and/or JQuery.

While many characters are "legal" for HTML, as a practical matter some should be avoided: colon, hash and slashes being other candidates.  As separators,   a dash seems fine, presumably underscore too.

Escape them, ban them, warn?  Not sure what would be best.

**Comment by davidfarmer** [comment]
SL2X replaces "bad id characters" in labels by underscores.  For example
\label{eqn:quadratic}
becomes eqn_quadratic

I just checked and for some reason period was not on my list of "bad id characters".  I just
added it.

I also convert all labels to ASCII.

I just do this on the fly, converting all labels and the contents of ref and eqref to
the "safe" version.  No need to give any warning.

To be super-careful, you could warn when there appear to be two identical
safe labels, which can happen if people use slightly crazy labels.

No need to ban them, but you could explain that an author label may not be used
literally if it goes outside the 64 safe ASCII characters.

You can close this issue if you agree.

**Comment by rbeezer** [comment]
Good to know SL2X is sanitizing.

Maybe I should do the same thing in MBX's basic template for this.  Can you point me to your bad characters?

xsltproc and xmllint will automatically detect and warn about duplicate IDs, so no need to do anything extra.

I'll close this issue **BUT** do you feel inclined to make the knowl Javascript anymore robust for anybody else who might be using it in some other way?  Your call, but that was my intent in making this.

Rob

**Comment by rbeezer** [comment]
Good to know SL2X is sanitizing.

Maybe I should do the same thing in MBX's basic template for this.  Can you 
point me to your bad characters?

xsltproc and xmllint will automatically detect and warn about duplicate IDs, so 
no need to do anything extra.

I'll close this issue **BUT** do you feel inclined to make the knowl Javascript 
anymore robust for anybody else who might be using it in some other way?  Your 
call, but that was my intent in making this.

Rob

**Comment by davidfarmer** [comment]
Currently I am thinking that it is okay for the knowl code to
assume the id is valid.

After converting to ASCII, the bad characters are replaced
by this Python substitution:

safe_text = re.sub(r"[: ~!@#$%^&*(){},+;/\\\'\".]","_",safe_text)

but I am thinking of just having it replace anythign that is not
a letter, number, underscore, or dash.  Because why don't I already
substitute for equals, pipe, greater than, or less than?  Probably
because I didn't encounter those yet.

**Comment by rbeezer** [comment]
Thanks, that helps.  I wouldn't have thought of all of those.
